### ISSUE TITLE
Panic while serving

### ISSUE THREAD

**Issue by columna1** [columna1/mdh-go#7]
While running this client the cache disk space filled up and it seemed to be evicting fine however after a while I started getting these
```2020/07/19 22:37:41 Cache hit for data/c5e8771b64330b2678d3abcaf74d95b2/R11.jpg
2020/07/19 22:37:41 http2: panic serving 111.125.110.32:37019: runtime error: invalid memory address or nil pointer derefe
rence
goroutine 228909023 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc00c82d068, 0xc00070bf8e, 0xc003f7b380)
        c:/go/src/net/http/h2_bundle.go:5713 +0x16b
panic(0x8cb360, 0xd4d340)
        c:/go/src/runtime/panic.go:969 +0x166
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/skl/skl.go:86
github.com/dgraph-io/badger/v2.(*DB).getMemTables(0xc000112d80, 0x0, 0x0, 0x0, 0x0)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:578 +0xd1
github.com/dgraph-io/badger/v2.(*DB).get(0xc000112d80, 0xc0060ca540, 0x35, 0x35, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:610 +0x7a
github.com/dgraph-io/badger/v2.(*Txn).Get(0xc003c39300, 0xc0000a0fc0, 0x2d, 0x30, 0x2d, 0x30, 0x9fe735)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/txn.go:409 +0xe7
main.handleCacheHit.func1(0xc003c39300, 0xc000060001, 0xc003c39300)
        C:/Users/columna1/go/src/github.com/columna1/mdh-go/main.go:285 +0x99
github.com/dgraph-io/badger/v2.(*DB).Update(0xc000112d80, 0xc00070b998, 0x0, 0x0)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/txn.go:698 +0x87
main.handleCacheHit(0xa16040, 0xc00c82d068, 0xc0029bb500, 0xc004322bb0, 0x3, 0x3)
        C:/Users/columna1/go/src/github.com/columna1/mdh-go/main.go:284 +0x31d
main.handleRequest(0xa16040, 0xc00c82d068, 0xc0029bb500)
        C:/Users/columna1/go/src/github.com/columna1/mdh-go/main.go:572 +0x8fc
net/http.HandlerFunc.ServeHTTP(0x97c7b8, 0xa16040, 0xc00c82d068, 0xc0029bb500)
        c:/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xd5e980, 0xa16040, 0xc00c82d068, 0xc0029bb500)
        c:/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0057f4000, 0xa16040, 0xc00c82d068, 0xc0029bb500)
        c:/go/src/net/http/server.go:2807 +0xa3
net/http.initALPNRequest.ServeHTTP(0xa173c0, 0xc003cc4360, 0xc0099ca380, 0xc0057f4000, 0xa16040, 0xc00c82d068, 0xc0029bb50
0)
        c:/go/src/net/http/server.go:3381 +0x8d
net/http.(*http2serverConn).runHandler(0xc003f7b380, 0xc00c82d068, 0xc0029bb500, 0xc005b445a0)
        c:/go/src/net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
        c:/go/src/net/http/h2_bundle.go:5454 +0x4e1
badger 2020/07/19 22:37:41 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2020/07/19 22:37:41 INFO: Running for level: 0
```
after about 5 mins it crashed with
```badger 2020/07/19 22:37:42 INFO: LOG Compact 0->1, del 3 tables, add 1 tables, took 847.987968ms
badger 2020/07/19 22:37:42 INFO: Compaction for level: 0 DONE
badger 2020/07/19 22:37:42 INFO: Force compaction on level 0 done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81328b]

goroutine 1 [running]:
github.com/dgraph-io/badger/v2.(*Item).Value(0x0, 0xc0095b5908, 0x0, 0x0)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/iterator.go:96 +0x3b
main.evictCache.func3(0xc003210280, 0xc005ed0000, 0xc003210280)
        C:/Users/columna1/go/src/github.com/columna1/mdh-go/main.go:198 +0x11a
github.com/dgraph-io/badger/v2.(*DB).View(0xc000112d80, 0xc0095b5a50, 0x0, 0x0)
        C:/Users/columna1/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/txn.go:685 +0x92
main.evictCache()
        C:/Users/columna1/go/src/github.com/columna1/mdh-go/main.go:196 +0x2c5
main.main()
        C:/Users/columna1/go/src/github.com/columna1/mdh-go/main.go:877 +0x55d
```
full log is attached
[fail.txt](https://github.com/columna1/mdh-go/files/4950032/fail.txt)

**Comment by columna1** [comment]
I believe the crash has been fixed, however there is a related problem that needs to be solved. When grabbing random keys the stream function takes much to long to pick a random key, this takes longer than the 1 second main loop so it goes through and calls the evict function again causing issues. I think the current solution is untenable and should be swapped out for something better. Perhaps iterating over the cache directory and picking a random chapter to delete using that.
